### example connections
### set the ip then uncomment
# [connection-1]
# kind = 'banana'
# ip = 'localhost'
# streamname = 'Command1'
# port = 6980

# [connection-2]
# kind = 'potato'
# ip = 'gamepc.local'
# streamname = 'Command1'
# port = 6980
